version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - server/.env
    environment:
      - DOMAIN=${DOMAIN:-http://localhost:3001}
      - HTTP_PROXY
      - HTTPS_PROXY
      - http_proxy
      - https_proxy
    volumes:
      - ./server/data.db:/app/server/data.db
      - ./server/uploads:/app/server/uploads
