services:
  - type: web
    name: tg-news-server
    runtime: node
    plan: free
    buildCommand: npm run install-all && npm run build --prefix client
    startCommand: node server/index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
  - type: static
    name: tg-news-client
    buildCommand: npm run build --prefix client
    staticPublishPath: client/dist
